export enum BadgeCondition {
  oneSightingReported,
  fiveSightingsReported,
  tenSightingsReported,
  twentySightingsReported,
  oneImageUploaded,
  fiveImagesUploaded,
  tenImagesUploaded,
  twentyImagesUploaded,
  oneCommentWritten,
  fiveCommentsWritten,
  tenCommentsWritten,
  twentyCommentsWritten,
  allBadgesUnlocked,
}
